general:
  label: 基本设置
  items:
    footer_logo:
      name: footer_logo
      label: 页尾 logo
      type: attachment
    search_page:
      name: search_page
      label: 搜索页地址
      type: text
    pjax:
      name: pjax
      label: PJAX 加速设置
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    dns:
      name: dns
      label: DNS 预解析加速
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    fast_click:
      name: fast_click
      label: 移动端点击延迟消除插件
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
photos:
  label: 相册页
  items:
    photos_style:
      name: photos_style
      label: 相册布局风格
      type: select
      default: justify
      options:
        - value: justify
          label: 合理布局
        - value: masonry
          label: 瀑布流布局
        - value: packery
          label: 填充式瀑布流布局（实验性）
    is_thumbnail:
      name: is_thumbnail
      label: 列表使用缩略图
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    photos_gutter:
      name: photos_gutter
      label: 图像之间的间距
      type: text
      data-type: long
      default: 10
    masonry_column:
      name: masonry_column
      label: 瀑布流列数(移动端始终为1)
      type: select
      default: 3
      options:
        - value: 2
          label: 2
        - value: 3
          label: 3
        - value: 4
          label: 4
        - value: 5
          label: 5
        - value: 6
          label: 6
        - value: 7
          label: 7
        - value: 8
          label: 8
    masonry_changer_min:
      name: masonry_changer_min
      label: 瀑布流切换功能最小列数
      type: select
      default: 3
      options:
        - value: 2
          label: 2
        - value: 3
          label: 3
        - value: 4
          label: 4
        - value: 5
          label: 5
        - value: 6
          label: 6
        - value: 7
          label: 7
        - value: 8
          label: 8
    masonry_changer_max:
      name: masonry_changer_max
      label: 瀑布流切换功能最大列数
      type: select
      default: 5
      options:
        - value: 2
          label: 2
        - value: 3
          label: 3
        - value: 4
          label: 4
        - value: 5
          label: 5
        - value: 6
          label: 6
        - value: 7
          label: 7
        - value: 8
          label: 8
style:
  label: 样式设置
  items:
    post_list:
      name: post_list
      label: 首页文章列表
      type: radio
      data-type: string
      default: three
      options:
        - value: three
          label: 三栏
        - value: one
          label: 单栏
    post_color:
      name: post_color
      label: 文章色块设置
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_picture:
      name: post_picture
      label: 文章题图设置
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_toc:
      name: post_toc
      label: 文章目录设置
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_highlight:
      name: post_highlight
      label: 代码高亮设置
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_mathjax:
      name: post_mathjax
      label: 文章 Mathjax 设置
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
sns:
  label: 社交资料设置
  items:
    weibo:
      name: weibo
      label: 微博链接
      type: text
    zhihu:
      name: zhihu
      label: 知乎链接
      type: text
    github:
      name: github
      label: GitHub 链接
      type: text
    twitter:
      name: twitter
      label: Twitter 链接
      type: text
